version: '3'

services:
  mail-service-dueit:
    container_name: mail-service-dueit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9090:9090'
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
        read_only: true
    networks:
      - docker-compose-dueit_dueit_network
networks:
  docker-compose-dueit_dueit_network:
    external: true
