# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: dueit-mail-service

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: SyaibanAhmadRamadhan
          password: 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
      - name: build and push
        run: |
          docker build . --tag ghcr.io/dueit-jasanya-aturuang/dueit-mail-service:1.0
          docker push ghcr.io/dueit-jasanya-aturuang/dueit-mail-service:1.0
